global:
  scrape_interval: 3s

  external_labels:
    monitor: "web-server"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "web-server-job"
    static_configs:
      - targets: ["app:8080"]