"""empty message

Revision ID: adc0d30fd074
Revises: 
Create Date: 2023-09-01 04:39:05.099078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc0d30fd074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('sale_type', sa.String(length=50), nullable=True),
    sa.Column('sold_date', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state_or_province', sa.String(length=50), nullable=True),
    sa.Column('zip_or_postal_code', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('beds', sa.String(length=50), nullable=True),
    sa.Column('baths', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('square_feet', sa.String(length=50), nullable=True),
    sa.Column('lot_size', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.String(length=50), nullable=True),
    sa.Column('days_on_market', sa.String(length=50), nullable=True),
    sa.Column('price_per_square_feet', sa.String(length=50), nullable=True),
    sa.Column('hoa_per_month', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('next_open_house_start_time', sa.String(length=50), nullable=True),
    sa.Column('next_open_house_end_time', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('mls_number', sa.String(length=50), nullable=True),
    sa.Column('favorite', sa.String(length=1), nullable=True),
    sa.Column('interested', sa.String(length=1), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_records')
    # ### end Alembic commands ###
