version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/webapp
  - source: applications/web-server/src/main/gunicorn-web.service
    destination: /etc/systemd/system/
  - source: applications/data-collector/src/main/gunicorn-collector.service
    destination: /etc/systemd/system/
hooks:
  AfterInstall:
    - location: build/venv.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: build/start_services.sh
      timeout: 300
      runas: root