version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/webapp
  - source: src/gunicorn.service
    destination: /etc/systemd/system/
hooks:
  BeforeInstall:
    - location: applications/web-server/src/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: applications/web-server/src/scripts/start_service.sh
      timeout: 300
      runas: root
