version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/webapp
  - source: applications/web-server/src/gunicorn-web.service
    destination: /etc/systemd/system/
  - source: applications/data-collector/src/gunicorn-collector.service
    destination: /etc/systemd/system/
hooks:
  BeforeInstall:
    - location: applications/web-server/src/scripts/venv.sh
      timeout: 300
      runas: root
    - location: applications/data-collector/src/scripts/venv.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: applications/web-server/src/scripts/start_service.sh
      timeout: 300
      runas: root
    - location: applications/data-collector/src/scripts/start_service.sh
      timeout: 300
      runas: root
